apiVersion: v1
kind: Pod
metadata:
  name: node-stresser
spec:
  nodeSelector:
    kubernetes.io/hostname: kind-worker 
  containers:
  - name: stress
    image: polinux/stress
    resources:
      limits:
        cpu: "2"
        memory: "1Gi"
    command: ["stress"]
    args: 
      - "--cpu"
      - "2"         
      - "--vm"
      - "1"          
      - "--vm-bytes"
      - "500M"       
      - "--timeout"
      - "300s"       