apiVersion: v1
kind: Pod
metadata:
  name: cpu9
spec:
  schedulerName: topsis-scheduler
  restartPolicy: Never
  containers:
  - name: stress
    image: polinux/stress
    command: ["stress"]
    args:
      - "--cpu"
      - "1"
    resources:
      requests:
        cpu: "100m"
        memory: "32Mi"
      limits:
        cpu: "100m"
        memory: "32Mi"